#!/usr/bin/env python3
"""Generate the Mac's schema catalog from authoritative proto files; never edit output."""
import base64
from pathlib import Path

root = Path(__file__).resolve().parents[2]
names = ('envelope-encrypted', 'inner-event-v2', 'notif-post', 'peer-receipt', 'relay-control')
rows = ['// Generated by macos/scripts/sync-schemas.py from proto/*.schema.json.',
        'import Foundation', 'enum ProtocolSchemas {', '    static let data: [String: Data] = [']
for name in names:
    encoded = base64.b64encode((root / 'proto' / (name + '.schema.json')).read_bytes()).decode('ascii')
    rows.append(f'        "{name}": Data(base64Encoded: "{encoded}")!,')
rows.extend(['    ]', '}', ''])
output = root / 'macos/Sources/TwinotifyKit/GeneratedSchemas.swift'
content = '\n'.join(rows)
if not output.exists() or output.read_text() != content:
    output.write_text(content)
