package expo.modules.phonesynccore.crypto

import android.content.Context
import androidx.datastore.preferences.core.byteArrayPreferencesKey
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.first

private val Context.cryptoDs by preferencesDataStore("phonesync_crypto")

/**
 * Persistence layer for the X25519 + Ed25519 keypairs generated by WrappedKeys.
 * Secret keys are AES-GCM sealed with the Keystore master key; public keys are
 * stored in plaintext (they're public).
 *
 * On first call, generates fresh keypairs and persists them. Subsequent calls
 * load and unseal the stored material.
 */
object CryptoStore {
    private val KEY_BOX_SECRET_CT = byteArrayPreferencesKey("box_secret_ct")
    private val KEY_BOX_SECRET_IV = byteArrayPreferencesKey("box_secret_iv")
    private val KEY_BOX_PUBLIC    = byteArrayPreferencesKey("box_public")
    private val KEY_SIGN_SECRET_CT = byteArrayPreferencesKey("sign_secret_ct")
    private val KEY_SIGN_SECRET_IV = byteArrayPreferencesKey("sign_secret_iv")
    private val KEY_SIGN_PUBLIC    = byteArrayPreferencesKey("sign_public")

    suspend fun loadOrGenerate(context: Context): Pair<BoxKeyPair, SignKeyPair> {
        val prefs = context.cryptoDs.data.first()
        val existingBox = prefs[KEY_BOX_PUBLIC]?.let { pub ->
            val ct = prefs[KEY_BOX_SECRET_CT] ?: return@let null
            val iv = prefs[KEY_BOX_SECRET_IV] ?: return@let null
            BoxKeyPair(pub, WrappedKeys.unseal(Sealed(ct, iv)))
        }
        val existingSign = prefs[KEY_SIGN_PUBLIC]?.let { pub ->
            val ct = prefs[KEY_SIGN_SECRET_CT] ?: return@let null
            val iv = prefs[KEY_SIGN_SECRET_IV] ?: return@let null
            SignKeyPair(pub, WrappedKeys.unseal(Sealed(ct, iv)))
        }
        if (existingBox != null && existingSign != null) return existingBox to existingSign

        val newBox = WrappedKeys.generateBox()
        val newSign = WrappedKeys.generateSign()
        val boxSealed = WrappedKeys.seal(newBox.secretKey)
        val signSealed = WrappedKeys.seal(newSign.secretKey)
        context.cryptoDs.edit { e ->
            e[KEY_BOX_SECRET_CT] = boxSealed.ciphertext
            e[KEY_BOX_SECRET_IV] = boxSealed.iv
            e[KEY_BOX_PUBLIC]    = newBox.publicKey
            e[KEY_SIGN_SECRET_CT] = signSealed.ciphertext
            e[KEY_SIGN_SECRET_IV] = signSealed.iv
            e[KEY_SIGN_PUBLIC]    = newSign.publicKey
        }
        return newBox to newSign
    }

    suspend fun rotate(context: Context) {
        context.cryptoDs.edit { it.clear() }
        loadOrGenerate(context)
    }
}
